### PR TITLE
Globe Preview Fix

### LINKED ISSUE #199: Globe Preview Render Fix
globe preview in practice and arcade selection is broken. fix it.

### LINKED ISSUE #226: Render Multiple Views to Different Screens
create the possibility of a comic-panel-style view of different renders perspectives, supporting deferred shading.

### PR DESCRIPTION
**Pull request by callidaria**
closes #199 
closes #226

### CODE REVIEW

File: script/menu/menu.cpp [hunk 1]
```diff
@@ -137,6 +145,23 @@ Menu::Menu(World* world,CCBManager* ccbm,CascabelBaseFeature* ccbf,float &progre
...
+	cam3d.front.x = cos(glm::radians(pitch))*cos(glm::radians(yaw));
+	cam3d.front.y = sin(glm::radians(pitch));
+	cam3d.front.z = cos(glm::radians(pitch))*sin(glm::radians(yaw));
+	cam3d.front = glm::normalize(cam3d.front);
+	cam3d.update();
+
+	// render globe
+	m_ccbf->r3d->prepare_pmesh(cam3d);
+	m_ccbf->r3d->render_pmsh(ridx_terra);
+}*/
```
Comment (callidaria) [inline script/menu/menu.cpp:163]: remove

File: script/menu/menu.cpp [hunk 2]
```diff
@@ -24,12 +24,19 @@ Menu::Menu(World* world,CCBManager* ccbm,CascabelBaseFeature* ccbf,float &progre
...
-	m_ccbf->r3d->add("./res/selection.obj","./res/fast_bullet.png","./res/none.png",
-			"./res/dnormal.png","./res/none.png",glm::vec3(0,0,1),.015f,glm::vec3(120,0,0));
+	// add globe scene
+	ridx_terra = m_ccbf->r3d->add_physical("./res/terra.obj","./res/terra/albedo.jpg",
+			"./res/terra/norm.png","./res/terra/materials.png","./res/none.png",glm::vec3(0),
+			1,glm::vec3(0));
+	glighting = Lighting();
+	glighting.add_sunlight({ glm::vec3(-50,25,25),glm::vec3(1),10.0f });
 	progress += sseq;
+	// TODO: add location indicator
```
Comment (callidaria) [inline script/menu/menu.cpp:34]: add a new location indication placeholder

File: script/menu/menu.cpp [hunk 3]
```diff
@@ -462,30 +487,23 @@ void Menu::render(FrameBuffer* game_fb,uint32_t &running,bool &reboot)
...
 	// calculate globe rotation towards preview location
 	glm::vec2 gRot = mls[i_ml].globe_rotation(lselect);
 	glm::mat4 model = glm::rotate(glm::mat4(1.0f),glm::radians(gRot.x),glm::vec3(1,0,0));
-	model = glm::rotate(model,glm::radians(gRot.y),glm::vec3(0,-1,0));
-	m_ccbf->r3d->s3d.upload_matrix("model",model);
+	m_ccbf->r3d->pml[ridx_terra].model = glm::rotate(model,glm::radians(gRot.y),glm::vec3(0,-1,0));
+
+	// render globe preview to target
+	m_ccbf->r3d->start_target(rtarget_id);
+	m_ccbf->frame->clear();
```
Comment (callidaria) [inline script/menu/menu.cpp:497]: autoclear when starting targets (isn't the clear method static?)

File: ccb/gfx/renderer3d.h [hunk 4]
```diff
@@ -10,13 +10,21 @@
...
+#include "../frm/gbuffer.h"
 #include "../fcn/buffer.h"
 
 constexpr uint8_t R3D_INDEX_REPEAT = 9;
 constexpr uint8_t R3D_ANIMATION_MAP_REPEAT = 16;
 
+struct Target3D {
+	GBuffer gbuffer;
+	FrameBuffer cbuffer;
+};
```
Comment (callidaria) [inline ccb/gfx/renderer3d.h:26]: change Target3D to DeferredTarget and cbuffer to dbuffer

File: ccb/gfx/renderer3d.cpp [hunk 5]
```diff
@@ -246,6 +247,98 @@ void Renderer3D::load(Camera3D cam3d,float &progress,float pseq)
 }
 // TODO: check validity of this loading approach. processing vertex lists ?twice
 
+/*
+	TODO
```
Comment (callidaria) [inline ccb/gfx/renderer3d.cpp:251]: do the documentation

**Review by callidaria — COMMENTED** [review]
i'm not convinced we can do much more at the moment, but hopefully later this will all come full circle

File: script/menu/menu.cpp (hunk 2 above)
Comment (callidaria) [reply script/menu/menu.cpp:34]: will be done in #233

File: ccb/gfx/renderer3d.cpp [hunk 6]
```diff
@@ -246,6 +247,113 @@ void Renderer3D::load(Camera3D cam3d,float &progress,float pseq)
...
+	glBindTexture(GL_TEXTURE_2D,rtargets[id].gbuffer.get_colour());
+	glActiveTexture(GL_TEXTURE1);
+	glBindTexture(GL_TEXTURE_2D,rtargets[id].gbuffer.get_position());
+	glActiveTexture(GL_TEXTURE2);
+	glBindTexture(GL_TEXTURE_2D,rtargets[id].gbuffer.get_normals());
+	glActiveTexture(GL_TEXTURE3);
+	glBindTexture(GL_TEXTURE_2D,rtargets[id].gbuffer.get_materials());
+	glActiveTexture(GL_TEXTURE7);
+	glBindTexture(GL_TEXTURE_2D,shadow_map);
+	// TODO: create single shadow maps for each target?
```
Comment (callidaria) [inline ccb/gfx/renderer3d.cpp:345]: this one will still cause major problems later

Comment (callidaria) [reply ccb/gfx/renderer3d.cpp:345]: no it won't, the projection doesn't depend on perspective

**Comment by callidaria** [comment]
yeah, right now mainly the intend counts. this is the basic idea for an actually good implementation later. the real challenge will be structuring so the technical debt for feature developing is not overwhelming in the future.
